
# Introduction

In Assignment 10 for our class, we looked at the use of Q-Learning and DRL learning thorough application to Blackjack (BJ). A Medium article, entitled "Blackjack, Stocks, and Reinforcement Learning: ML for Risk Management" [1] was provided for us to review.  For the follwing reasons, I found the assigned article to be dissapointing:
1. The results obtained by the author were unrealistic. For Q-learning, the author demonstrated a reward per episode of -68/100, or -68%. For DRL, the author demonstrated an expected return of 643%/100 episode, or +6.43% per episode. Blackjack is a well studied game that is believed to have an optimal strategy adn these values are not consitent with that prior analysis.  Without counting cards or other cheating methods, optimally played BJ has a player expected value of about -0.5%, which implies a house advantage.  Even with cheating, the player EV can only be brought to +1.0%.  This implies
2. The Open AI Gym BJ environment has some shortcomings for teaching RL.  First, the output of the environment does not reveal player or dealer cards, making understanding the workings of the model challenging.  Second, the environment only offers a simplified game of BlackJack, which does not have Splits, Doubling Down, or Surrenders incorporated.  This simplified model is useful for implementing RL tests but it also reduced the optimal player EV.
3. The assigned article output is challenging to interpret for a few reasons.  First the many images of BJ games are hard to understand and dominate the output.  Second, the author does nto compare his alogithms to any baseline, so performance is diffcult to interpret.


To address these concerns, I decided to provide the following:
1. A new implmentation of BJ, which allows for
2. An analysis of the naive (or random) player for blavkjack
3. An analysis of the optimal strategy for Blackjack
4. Impletementation of QL and DRL for BJ with comparision to naive and optimal strategies
5. An analysis of where the asigned article went wrong.



# 6D Analysis

## Decomposition

Decomposition of the BJ problem addressed herein is the nature of the project.  The main hypothesis of the project is that QL will produce superior results to DRL as QL is a more exact technique that works in smaller state spaces such as BJ.  We have therefore tested both algorithms and present results.  Additioanlly, by redesigning the BJ environment to allow for a closer look inside the "black box", this may allow for more insights as to where the previous effort went wrong.

## Domain Expertise

This exercise has made me a Domain expert on BJ and optimal strategies.  Aditionally, both literatre and web content provide optimal strategies for the game which can be considered to be the Expert.  The goal of this project is to see how close our created model can come to the Expert but it is not reasonalbe to assume RL techniques will surpuass Expert results.

## Data

Data for this project comes from the game itself.  No external sources were required.

## Design



## Diagnosis

One purpose of this project is diagnosis of the issues with the assigned article.  Comparision to Expert and naive baselines will allow for detection of

## Deployment

Although beyond the scope of this article, deployment of this model could be performed by allowing outside users to find optimal plays

# Naive and Expert model assessment

In [6]:
import pandas as pd

import utils
import blackjack as bj


game = bj.Blackjack()
#utils.play_bj_random(game)

# Q Learning Implementation

# DRL Implementation

# Analysis

In [7]:
from blackjack import Blackjack



In [5]:
game = Blackjack()


In [6]:
game.deal()


('H5', '6', 0, False)

# References

1. https://towardsdatascience.com/playing-blackjack-using-model-free-reinforcement-learning-in-google-colab-aa2041a2c13d
1. https://trevormcguire.medium.com/blackjack-stocks-and-reinforcement-learning-ea4014115aeb


# Envrionment packages



In [2]:
import gym

In [334]:
env = gym.make("Blackjack-v1")

/Users/hrose/PycharmProjects/BlackJack/venv/lib/python3.10/site-packages/gym/core.py:329: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/Users/hrose/PycharmProjects/BlackJack/venv/lib/python3.10/site-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [143]:
env.reset()

(12, 5, False)

In [333]:
env.reset()
env.step(0)

((15, 4, False), -1.0, True, {})

In [328]:
env.spec.id

'Blackjack-v1'

In [329]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [330]:
class DQN(nn.Module):
    def __init__(self, state_size = 3, action_size = 2):
        super(DQN, self).__init__()
        self.fc1 = nn.Linear(state_size, 64)
        self.fc2 = nn.Linear(64, 64)
        self.fc3 = nn.Linear(64, action_size)

    def forward(self, state):
        x = F.relu(self.fc1(state))
        x = F.relu(self.fc2(x))
        return self.fc3(x)

In [331]:
net = DQN()

In [332]:
import numpy as np

test_in = np.array([1,2,3])
test_in

array([1, 2, 3])

In [26]:
test_in.shape

(3,)

In [27]:
net(test_in).shape

TypeError: linear(): argument 'input' (position 1) must be Tensor, not numpy.ndarray

In [10]:
test_in

tensor([[-0.1954,  1.1420, -0.0674],
        [ 0.9946, -0.3488, -0.5642]])

In [11]:
test_in.shape

torch.Size([2, 3])

In [12]:
net(test_in).shape

torch.Size([2, 2])

In [29]:
import random



0.7730318168810721

In [32]:
random.random()

0.32557896658185126

In [40]:
from collections import deque, namedtuple


In [35]:
d = deque(maxlen=3)
d.append(1)
d.append(2)
d.append(3)


In [36]:
d

deque([1, 2, 3], maxlen=3)

In [37]:
d.append(4)

In [38]:
d

deque([2, 3, 4], maxlen=3)

In [76]:
Transition = namedtuple('Transition', ('state', 'action', 'next_state', 'reward', 'done'))


class ReplayMemory():
    """
    Class to create memory for DQN training
    """

    def __init__(self, capacity):
        self.memory = deque(maxlen=capacity)

    def push(self, *args):
        """
        Method to allow a Transition to be added to the deque.
        :param args: arguments for adding to a Transition named tuple to be added to the list
                        should be state, action, reward, next_state, done where:
                        state: tensor, action: int, reward: float, next_state: tensor, done: bool
        :return: None
        """
        self.memory.append(Transition(*args))

    def sample(self, batch_size):
        """
        Method to return batch of Transitions randomly selected without replacement.
        :param batch_size: int - Length of batch
        :return:
        """
        s =  random.sample(self.memory, batch_size)
        batches = Transition(*zip(*s))
        return batches


    def __len__(self):
        return len(self.memory)

mem = ReplayMemory(3)
mem.push(torch.tensor([1,2]),2,3,torch.tensor([3,4]),5)
mem.push(torch.tensor([1,3]),7,8,torch.tensor([3,5]),10)
mem.push(torch.tensor([1,4]), 12, 13, torch.tensor([3,6]), 15)
mem.memory

deque([Transition(state=tensor([1, 2]), action=2, next_state=3, reward=tensor([3, 4]), done=5),
       Transition(state=tensor([1, 3]), action=7, next_state=8, reward=tensor([3, 5]), done=10),
       Transition(state=tensor([1, 4]), action=12, next_state=13, reward=tensor([3, 6]), done=15)],
      maxlen=3)

tensor([1, 2])

In [81]:
mem.sample(2)

AttributeError: can't set attribute

In [112]:
a = (torch.tensor([1,2,3]), torch.tensor([4,5,6]))

a+b

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([1, 2, 3]), tensor([4, 5, 6]))

In [114]:
b = torch.stack(a)
b

tensor([[1, 2, 3],
        [4, 5, 6]])

In [110]:
c = (1, 2, 3)
d = torch.tensor(c).unsqueeze(1)
d.size()

torch.Size([3, 1])

In [88]:
a = torch.randn([10, 2])
a

tensor([[-0.6338,  0.4557],
        [-1.5007, -1.0967],
        [ 0.7038,  0.1803],
        [-0.6902, -0.6281],
        [-0.5288,  2.0306],
        [ 1.1666, -0.4851],
        [-0.2686, -0.3346],
        [ 0.3593, -0.8970],
        [-0.5768,  1.0790],
        [-0.4323, -0.3424]])

In [96]:
a.max(1, keepdim=True)

torch.return_types.max(
values=tensor([[ 0.4557],
        [-1.0967],
        [ 0.7038],
        [-0.6281],
        [ 2.0306],
        [ 1.1666],
        [-0.2686],
        [ 0.3593],
        [ 1.0790],
        [-0.3424]]),
indices=tensor([[1],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1],
        [1]]))

In [99]:
index = a.max(1, keepdim=True).indices
index

tensor([[1],
        [1],
        [0],
        [1],
        [1],
        [0],
        [0],
        [0],
        [1],
        [1]])

In [121]:
(1-index)

tensor([[0],
        [0],
        [1],
        [0],
        [0],
        [1],
        [1],
        [1],
        [0],
        [0]])

In [100]:
torch.gather(a, 1, index)

tensor([[ 0.4557],
        [-1.0967],
        [ 0.7038],
        [-0.6281],
        [ 2.0306],
        [ 1.1666],
        [-0.2686],
        [ 0.3593],
        [ 1.0790],
        [-0.3424]])

In [115]:
f = torch.tensor([True, False, True], dtype=int)
f

tensor([1, 0, 1])

In [122]:
env.reset()

NameError: name 'env' is not defined